gesdinet_jwt_refresh_token:
    refresh_token_class: App\Entity\RefreshToken
    user_provider: security.user.provider.concrete.app_user_provider
    user_identity_field: id
    ttl: 269200
    ttl_update: true
    

    cookie:
      enabled: true
      same_site: lax               # default value
      path: /                      # default value
      domain: null                 # default value
      http_only: false             # default value
      secure: true                 # default value
      remove_token_from_body: true # default value