version: "3" 
services:

  database:
    image: mysql
    container_name: db-mdt-offline
    restart: always
    volumes:
      - db-mdt-offline:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    networks:
      - dev   
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin_mdt-offline
    restart: always
    depends_on:
      - database
    ports:
      - 3301:80
    environment:
      PMA_HOST: database
    networks:
      - dev
      
  maildev:
    image: maildev/maildev

    command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
    ports:
      - "5500:80"
    restart: always
    networks:
      - dev   
  www:
    build: docker
    container_name: www_mdt_offline
    ports:
      - "3000:80"
    volumes: 
      - ./docker/vhosts:/etc/apache2/sites-enabled
      - ./:/var/www
    restart: always
    environment: 
      DATABASE_URL: mysql://root:@db-mdt-offline:3306/mdt-offline
      APP_ENV: prod
      APP_SECRET: 8f76b5aa095e32129b33d3fdd33691b7
    networks:
      - dev
networks:
  dev:    
volumes:
  db-mdt-offline:

