name: Deploiment continueement

on:
  push: 
   branches:
    - main

jobs:
  deploy: 
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        
      - name: APT UPDATE and INSTALL PACKAGE SERVER_VERSION   
        run:
          git pull 
      - name: INTALL and BUILD PROJECT
        run:
          npm run build
