name: Deploiment continueement

on:
  push: 
   branches:
    - main

jobs:
  deploy: 
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
       # APT UPDATE and INSTALL PACKAGE SERVER_VERSION    
      - name: RETRIEVE LAST UPDATE REPO   
        run:
          git pull 
      - name: NPM INTALL and BUILD PROJECT
        run:
          composer install && php bin/console d:m:m -n && npm install -f && npm run build

      