name: Deploiment continueement

on:
  push: 
   branches:
    - main

jobs:
  deploy: 
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        
      - name: APT UPDATE and INSTALL PACKAGE SERVER_VERSION
        
        run :
          git pull && composer install && npm install php bin/console && bin/console d:m:m -n  && npm run build
